'use client'

/**
 * VideoRoom — Agora RTC video/voice/chat consultation room
 * 
 * Supports all 3 consultation types:
 *   - video: Camera + mic, both sides see each other
 *   - voice: Mic only, no camera
 *   - chat:  Text only (no AV, separate implementation possible)
 * 
 * Agora channel = consultationId (set by backend on initiation)
 * Token = generated by backend using Agora App Certificate
 */

import { useEffect, useState, useRef, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { motion, AnimatePresence } from 'framer-motion'
import AgoraRTC, {
  IAgoraRTCClient,
  IAgoraRTCRemoteUser,
  ILocalVideoTrack,
  ILocalAudioTrack,
  ICameraVideoTrack,
  IMicrophoneAudioTrack,
} from 'agora-rtc-sdk-ng'
import { apiFetch } from '@/lib/api'

AgoraRTC.setLogLevel(4) // NONE in production to prevent console noise

type ConnectionState = 'connecting' | 'connected' | 'disconnected' | 'error'
type ConsultType = 'video' | 'voice' | 'chat'

interface VideoRoomProps {
  consultationId: string
  channel: string
  token: string | null
  uid: number
  appId: string
  type: ConsultType
  /** Whose seat this is — drives the waiting-room copy. */
  viewerRole?: 'client' | 'lawyer'
  /** Fired once the local user has left, so the page can prompt for a review. */
  onEnded?: () => void
}

// ── Duration timer ─────────────────────────────────────────────────────────────
function useTimer() {
  const [seconds, setSeconds] = useState(0)
  const interval = useRef<NodeJS.Timeout | null>(null)
  const start = useCallback(() => {
    if (interval.current) return
    interval.current = setInterval(() => setSeconds(s => s + 1), 1000)
  }, [])
  const stop = useCallback(() => {
    if (interval.current) { clearInterval(interval.current); interval.current = null }
  }, [])
  useEffect(() => () => { stop() }, [stop])
  const fmt = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`
  return { seconds, fmt, start, stop }
}

// ── Icon components ────────────────────────────────────────────────────────────
function IconMicOn() {
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="w-5 h-5"><path d="M12 1a3 3 0 00-3 3v8a3 3 0 006 0V4a3 3 0 00-3-3z"/><path d="M19 10v2a7 7 0 01-14 0v-2M12 19v4M8 23h8" strokeLinecap="round" strokeLinejoin="round"/></svg>
}
function IconMicOff() {
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="w-5 h-5"><line x1="1" y1="1" x2="23" y2="23" strokeLinecap="round"/><path d="M9 9v3a3 3 0 005.12 2.12M15 9.34V4a3 3 0 00-5.94-.6"/><path d="M17 16.95A7 7 0 015 12v-2M12 19v4M8 23h8" strokeLinecap="round" strokeLinejoin="round"/></svg>
}
function IconCamOn() {
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="w-5 h-5"><polygon points="23 7 16 12 23 17 23 7"/><rect x="1" y="5" width="15" height="14" rx="2" ry="2"/></svg>
}
function IconCamOff() {
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="w-5 h-5"><path d="M16 16v1a2 2 0 01-2 2H3a2 2 0 01-2-2V7a2 2 0 012-2h2m5.66 0H14a2 2 0 012 2v3.34l1 1L23 7v10"/><line x1="1" y1="1" x2="23" y2="23" strokeLinecap="round"/></svg>
}
function IconEndCall() {
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" className="w-5 h-5"><path d="M10.68 13.31a16 16 0 003.41 2.6l1.27-1.27a2 2 0 012.11-.45 12.84 12.84 0 002.81.7 2 2 0 012 2v3a2 2 0 01-2.18 2 19.79 19.79 0 01-8.63-3.07A19.42 19.42 0 013.43 9.65 19.86 19.86 0 01.36 1a2 2 0 012-2.18h3a2 2 0 012 1.72 12.84 12.84 0 00.7 2.81 2 2 0 01-.45 2.11L6.18 6.77a16 16 0 002.6 3.41M23 1L1 23" strokeLinecap="round" strokeLinejoin="round"/></svg>
}

// ── Video tile ─────────────────────────────────────────────────────────────────
function VideoTile({
  track, label, muted, isLocal, noCamera,
}: {
  track: ILocalVideoTrack | null
  label: string
  muted?: boolean
  isLocal?: boolean
  noCamera?: boolean
}) {
  const ref = useRef<HTMLDivElement>(null)
  useEffect(() => {
    if (!track || !ref.current || noCamera) return
    track.play(ref.current)
    return () => { track.stop() }
  }, [track, noCamera])

  return (
    <div className="relative w-full h-full bg-[#0A0D14] rounded-2xl overflow-hidden flex items-center justify-center">
      {noCamera || !track ? (
        <div className="flex flex-col items-center gap-3">
          <div className="w-16 h-16 rounded-full bg-[#C9A227]/20 flex items-center justify-center">
            <svg className="w-8 h-8 text-[#C9A227]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.5">
              <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
            </svg>
          </div>
          <p className="text-slate-500 text-sm">Camera off</p>
        </div>
      ) : (
        <div ref={ref} className="w-full h-full" />
      )}
      {/* Label */}
      <div className="absolute bottom-3 left-3 flex items-center gap-1.5">
        <span className="text-xs font-medium text-white bg-black/60 backdrop-blur-sm px-2 py-1 rounded-md">
          {label}{isLocal ? ' (You)' : ''}
        </span>
        {muted && (
          <span className="p-1 bg-rose-500/80 rounded-md">
            <IconMicOff />
          </span>
        )}
      </div>
    </div>
  )
}

// ── Main VideoRoom ─────────────────────────────────────────────────────────────
export default function VideoRoom({ consultationId, channel, token, uid, appId, type, viewerRole = 'client', onEnded }: VideoRoomProps) {
  const router = useRouter()
  const timer = useTimer()
  const clientRef = useRef<IAgoraRTCClient | null>(null)

  const [connState, setConnState] = useState<ConnectionState>('connecting')
  const [connError, setConnError] = useState('')
  const [remoteUsers, setRemoteUsers] = useState<IAgoraRTCRemoteUser[]>([])

  const [localVideo, setLocalVideo] = useState<ICameraVideoTrack | null>(null)
  const [localAudio, setLocalAudio] = useState<IMicrophoneAudioTrack | null>(null)
  const [micEnabled,  setMicEnabled]  = useState(true)
  const [camEnabled,  setCamEnabled]  = useState(type === 'video')
  const [ending, setEnding] = useState(false)
  const [ended,  setEnded]  = useState(false)

  const isVideo = type === 'video'
  const isVoice = type === 'voice' || type === 'video'

  // ── Setup: create tracks + join channel ─────────────────────────────────────
  useEffect(() => {
    let client: IAgoraRTCClient
    let audioTrack: IMicrophoneAudioTrack | null = null
    let videoTrack: ICameraVideoTrack | null = null

    async function init() {
      try {
        client = AgoraRTC.createClient({ mode: 'rtc', codec: 'vp8' })
        clientRef.current = client

        // Event listeners for remote users
        client.on('user-published', async (user, mediaType) => {
          await client.subscribe(user, mediaType)
          setRemoteUsers(prev => {
            const exists = prev.find(u => u.uid === user.uid)
            return exists ? prev.map(u => u.uid === user.uid ? user : u) : [...prev, user]
          })
          if (mediaType === 'audio') user.audioTrack?.play()
        })
        client.on('user-unpublished', (user, mediaType) => {
          setRemoteUsers(prev => prev.map(u => u.uid === user.uid ? user : u))
        })
        client.on('user-left', user => {
          setRemoteUsers(prev => prev.filter(u => u.uid !== user.uid))
        })
        client.on('connection-state-change', (state) => {
          if (state === 'CONNECTED') { setConnState('connected'); timer.start() }
          if (state === 'DISCONNECTED') setConnState('disconnected')
        })

        // Create local media tracks
        if (isVoice) {
          audioTrack = await AgoraRTC.createMicrophoneAudioTrack()
          setLocalAudio(audioTrack)
        }
        if (isVideo) {
          videoTrack = await AgoraRTC.createCameraVideoTrack({ optimizationMode: 'motion' })
          setLocalVideo(videoTrack)
        }

        // Join channel
        await client.join(appId, channel, token, uid || null)

        // Publish tracks
        const tracks = [audioTrack, videoTrack].filter(Boolean) as (ILocalAudioTrack | ILocalVideoTrack)[]
        if (tracks.length) await client.publish(tracks)

        setConnState('connected')
        timer.start()
      } catch (err: any) {
        console.error('[VideoRoom] init error:', err)
        setConnError(err.message || 'Failed to connect to the session')
        setConnState('error')
      }
    }

    init()

    return () => {
      audioTrack?.close()
      videoTrack?.close()
      client?.leave().catch(() => {})
    }
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  // ── Controls ─────────────────────────────────────────────────────────────────
  const toggleMic = useCallback(async () => {
    if (!localAudio) return
    const next = !micEnabled
    await localAudio.setEnabled(next)
    setMicEnabled(next)
  }, [localAudio, micEnabled])

  const toggleCam = useCallback(async () => {
    if (!localVideo) return
    const next = !camEnabled
    await localVideo.setEnabled(next)
    setCamEnabled(next)
  }, [localVideo, camEnabled])

  const endCall = useCallback(async () => {
    setEnding(true)
    try {
      // Notify backend the session ended
      await apiFetch(`/api/consultations/${consultationId}/end`, { method: 'POST' })
        .catch(() => {}) // non-blocking — don't fail if endpoint not yet implemented
      localAudio?.close()
      localVideo?.close()
      await clientRef.current?.leave().catch(() => {})
      timer.stop()
      setEnded(true)
      onEnded?.()
    } catch {
      setEnded(true)
      onEnded?.()
    }
  }, [consultationId, localAudio, localVideo, timer, onEnded])

  // ── Ended screen ──────────────────────────────────────────────────────────────
  if (ended) {
    return (
      <div className="min-h-screen bg-[#060810] flex items-center justify-center px-4">
        <motion.div
          initial={{ scale: 0.9, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          className="text-center max-w-sm"
        >
          <div className="w-16 h-16 rounded-full bg-[#C9A227]/15 flex items-center justify-center mx-auto mb-5">
            <svg className="w-8 h-8 text-[#C9A227]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.5">
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <h2 className="text-2xl font-bold text-white mb-2">Session Ended</h2>
          <p className="text-slate-400 text-sm mb-1">Duration: <span className="text-white font-medium">{timer.fmt}</span></p>
          <p className="text-slate-500 text-xs mb-8">
            Total: {timer.seconds < 60 ? `${timer.seconds} seconds` : `${Math.floor(timer.seconds / 60)} min ${timer.seconds % 60} sec`}
          </p>
          <button
            onClick={() => router.push('/talk-to-lawyer')}
            className="w-full h-11 rounded-xl bg-[#C9A227] text-[#060810] font-semibold text-sm hover:bg-[#E5C050] transition-colors"
          >
            Back to Lawyers
          </button>
        </motion.div>
      </div>
    )
  }

  // ── Error screen ──────────────────────────────────────────────────────────────
  if (connState === 'error') {
    return (
      <div className="min-h-screen bg-[#060810] flex items-center justify-center px-4">
        <div className="text-center max-w-sm">
          <div className="w-14 h-14 rounded-full bg-rose-500/10 flex items-center justify-center mx-auto mb-4">
            <svg className="w-7 h-7 text-rose-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <h2 className="text-white font-semibold mb-2">Connection Failed</h2>
          <p className="text-slate-400 text-sm mb-1">{connError}</p>
          <p className="text-slate-600 text-xs mb-5">Check that your camera and microphone permissions are allowed.</p>
          <button
            onClick={() => window.location.reload()}
            className="px-5 py-2.5 rounded-lg bg-[#C9A227] text-[#060810] font-semibold text-sm mr-2"
          >
            Retry
          </button>
          <button
            onClick={() => router.push('/talk-to-lawyer')}
            className="px-5 py-2.5 rounded-lg bg-white/10 text-white text-sm"
          >
            Go Back
          </button>
        </div>
      </div>
    )
  }

  // ── Main room UI ───────────────────────────────────────────────────────────────
  const remoteUser = remoteUsers[0] || null

  return (
    <div className="min-h-screen bg-[#060810] flex flex-col">

      {/* Top bar */}
      <div className="flex items-center justify-between px-5 py-3 bg-[#0A0D14]/80 backdrop-blur-sm border-b border-white/5 z-10">
        <div className="flex items-center gap-3">
          <div className={`w-2 h-2 rounded-full ${connState === 'connected' ? 'bg-emerald-400 animate-pulse' : 'bg-amber-400 animate-pulse'}`} />
          <span className="text-sm text-white font-medium capitalize">{type} Consultation</span>
        </div>
        <div className="flex items-center gap-3">
          {connState === 'connected' && (
            <span className="text-sm font-mono text-[#C9A227] tabular-nums">{timer.fmt}</span>
          )}
          {connState === 'connecting' && (
            <span className="text-xs text-slate-400 flex items-center gap-2">
              <span className="w-3 h-3 border-2 border-slate-400/30 border-t-slate-400 rounded-full animate-spin" />
              Connecting…
            </span>
          )}
        </div>
        <div className="text-xs text-slate-500 font-mono">
          {remoteUsers.length > 0 ? `${remoteUsers.length + 1} participant${remoteUsers.length > 0 ? 's' : ''}` : (viewerRole === 'lawyer' ? 'Waiting for client…' : 'Waiting for lawyer…')}
        </div>
      </div>

      {/* Video area */}
      <div className="flex-1 relative overflow-hidden">

        {/* Remote user — main view */}
        {isVideo ? (
          <div className="w-full h-full p-3">
            {remoteUser ? (
              <div className="w-full h-full">
                {remoteUser.videoTrack ? (
                  <RemoteVideoTile track={remoteUser.videoTrack} label="Lawyer" />
                ) : (
                  <VideoTile track={null} label="Lawyer" noCamera />
                )}
              </div>
            ) : (
              <div className="w-full h-full flex flex-col items-center justify-center text-center gap-4">
                <div className="w-16 h-16 rounded-full bg-[#C9A227]/10 flex items-center justify-center">
                  <svg className="w-8 h-8 text-[#C9A227]/50" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.5">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                  </svg>
                </div>
                <div>
                  <p className="text-white font-medium mb-1">
                    {viewerRole === 'lawyer' ? 'Waiting for the client to join…' : 'Waiting for the lawyer to join…'}
                  </p>
                  <p className="text-slate-500 text-sm">
                    {viewerRole === 'lawyer'
                      ? 'The client has been notified and will join shortly.'
                      : 'The lawyer has been notified and will join shortly.'}
                  </p>
                </div>
                <div className="flex gap-1.5">
                  {[0,1,2].map(i => (
                    <span key={i} className="w-2 h-2 rounded-full bg-[#C9A227]/40 animate-bounce" style={{ animationDelay: `${i * 0.15}s` }} />
                  ))}
                </div>
              </div>
            )}
          </div>
        ) : (
          /* Voice-only / chat: centered status card */
          <div className="flex-1 flex items-center justify-center p-8">
            <div className="text-center">
              <div className={`w-24 h-24 rounded-full mx-auto mb-6 flex items-center justify-center relative ${
                remoteUsers.length > 0 ? 'bg-emerald-500/10' : 'bg-[#C9A227]/10'
              }`}>
                <svg className={`w-12 h-12 ${remoteUsers.length > 0 ? 'text-emerald-400' : 'text-[#C9A227]/60'}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="1.5">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 6.75c0 8.284 6.716 15 15 15h2.25a2.25 2.25 0 002.25-2.25v-1.372c0-.516-.351-.966-.852-1.091l-4.423-1.106c-.44-.11-.902.055-1.173.417l-.97 1.293c-.282.376-.769.542-1.21.38a12.035 12.035 0 01-7.143-7.143c-.162-.441.004-.928.38-1.21l1.293-.97c.363-.271.527-.734.417-1.173L6.963 3.102a1.125 1.125 0 00-1.091-.852H4.5A2.25 2.25 0 002.25 4.5v2.25z" />
                </svg>
                {remoteUsers.length > 0 && (
                  <span className="absolute -top-1 -right-1 w-5 h-5 rounded-full bg-emerald-500 flex items-center justify-center">
                    <span className="w-2 h-2 rounded-full bg-white animate-pulse" />
                  </span>
                )}
              </div>
              <p className="text-xl font-semibold text-white mb-2">
                {remoteUsers.length > 0 ? 'Connected' : (viewerRole === 'lawyer' ? 'Waiting for Client…' : 'Waiting for Lawyer…')}
              </p>
              <p className="text-slate-400 text-sm">
                {remoteUsers.length > 0
                  ? `Voice call in progress — ${timer.fmt}`
                  : 'The lawyer has been notified'}
              </p>
              {!micEnabled && (
                <div className="mt-4 inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-rose-500/10 border border-rose-500/20">
                  <IconMicOff />
                  <span className="text-xs text-rose-400">Microphone muted</span>
                </div>
              )}
            </div>
          </div>
        )}

        {/* Local video: picture-in-picture (video mode only) */}
        {isVideo && localVideo && (
          <div className="absolute bottom-20 right-5 w-32 h-44 rounded-xl overflow-hidden border-2 border-white/15 shadow-2xl z-20">
            <LocalVideoTile track={localVideo} camEnabled={camEnabled} />
          </div>
        )}
      </div>

      {/* Control bar */}
      <div className="flex items-center justify-center gap-4 py-5 px-6 bg-[#0A0D14]/90 backdrop-blur-sm border-t border-white/5">

        {/* Mic toggle */}
        {isVoice && (
          <button
            onClick={toggleMic}
            className={`w-12 h-12 rounded-full flex items-center justify-center transition-all ${
              micEnabled
                ? 'bg-white/10 border border-white/15 text-white hover:bg-white/15'
                : 'bg-rose-500 border border-rose-400 text-white'
            }`}
            title={micEnabled ? 'Mute microphone' : 'Unmute microphone'}
          >
            {micEnabled ? <IconMicOn /> : <IconMicOff />}
          </button>
        )}

        {/* Camera toggle (video only) */}
        {isVideo && (
          <button
            onClick={toggleCam}
            className={`w-12 h-12 rounded-full flex items-center justify-center transition-all ${
              camEnabled
                ? 'bg-white/10 border border-white/15 text-white hover:bg-white/15'
                : 'bg-rose-500 border border-rose-400 text-white'
            }`}
            title={camEnabled ? 'Stop camera' : 'Start camera'}
          >
            {camEnabled ? <IconCamOn /> : <IconCamOff />}
          </button>
        )}

        {/* End call */}
        <button
          onClick={endCall}
          disabled={ending}
          className="w-14 h-14 rounded-full bg-rose-500 hover:bg-rose-600 flex items-center justify-center text-white transition-all shadow-lg shadow-rose-500/30 disabled:opacity-60"
          title="End consultation"
        >
          {ending
            ? <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            : <IconEndCall />}
        </button>

        {/* Timer display */}
        <div className="w-20 text-center">
          <p className="text-sm font-mono text-slate-300 tabular-nums">{timer.fmt}</p>
          <p className="text-xs text-slate-600 mt-0.5">duration</p>
        </div>
      </div>
    </div>
  )
}

// ── Remote video tile (subscribes to Agora remote track) ─────────────────────
function RemoteVideoTile({ track, label }: { track: any; label: string }) {
  const ref = useRef<HTMLDivElement>(null)
  useEffect(() => {
    if (!track || !ref.current) return
    track.play(ref.current)
    return () => { try { track.stop() } catch {} }
  }, [track])
  return (
    <div className="relative w-full h-full bg-[#0A0D14] rounded-2xl overflow-hidden">
      <div ref={ref} className="w-full h-full" />
      <div className="absolute bottom-3 left-3">
        <span className="text-xs font-medium text-white bg-black/60 backdrop-blur-sm px-2 py-1 rounded-md">{label}</span>
      </div>
    </div>
  )
}

// ── Local video PiP ───────────────────────────────────────────────────────────
function LocalVideoTile({ track, camEnabled }: { track: ICameraVideoTrack; camEnabled: boolean }) {
  const ref = useRef<HTMLDivElement>(null)
  useEffect(() => {
    if (!track || !ref.current) return
    if (camEnabled) track.play(ref.current)
    else track.stop()
  }, [track, camEnabled])
  return (
    <div className="w-full h-full bg-[#0A0D14] flex items-center justify-center">
      {camEnabled
        ? <div ref={ref} className="w-full h-full" />
        : <div className="text-slate-600 text-xs text-center p-2">Camera off</div>}
    </div>
  )
}
